version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: flashbid-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: flashbid-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  redis:
    image: redis:5.0.3
    container_name: flashbid-redis
    hostname: flashbid
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flashbid-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    image: junan01/flashbid-main-server:latest
    container_name: flashbid-server
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/geoip/GeoLite2-City.mmdb:/app/geoip/database.mmdb
      - ./google_bucket_key.json:/app/google_bucket_key.json
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/flashbid_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}

      JWT_SECRET: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      GEOIP_DATABASE_PATH: file:/app/geoip/database.mmdb

      SPRING_CLOUD_GCP_STORAGE_CREDENTIALS_LOCATION: file:/app/google_bucket_key.json
      GOOGLE_APPLICATION_CREDENTIALS: /app/google_bucket_key.json

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest


  ranking-app:
      image: junan01/flashbid-ranking-server:latest
      container_name: flashbid-ranking-server
      restart: always
      depends_on:
        - redis
        - rabbitmq
      ports:
        - "8081:8081"
      environment:
        JWT_SECRET: ${JWT_SECRET_KEY}

        SPRING_DATA_REDIS_HOST: redis
        SPRING_DATA_REDIS_PORT: 6379

        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: 5672

        SPRING_RABBITMQ_USERNAME: guest
        SPRING_RABBITMQ_PASSWORD: guest
